# COLORS: Foreground Background buri (bold, underlined, reverse ,italic)

# UI ELEMENTS
ColorColumn: '- cursorLine'
CursorColumn: '- cursorLine'
Conceal: 'darkPurp2'  # IDK what these is
Cursor: 'background grey'
CursorIM: '@Cursor' # IDK what this is
CursorLine: '- cursorLine'
CursorLineNr: 'grey2 cursorLine'
Directory: 'cyan'
DiffAdd: 'green visualSel'
DiffChange: 'orange visualSel'
DiffDelete: 'red visualSel'
DiffText: 'yellow visualSel'
EndOfBuffer: 'darkPurp background'
TermCursor: '@Cursor'
#TermCursorNC: ''
ErrorMsg: 'red'
VertSplit: 'pureBlack pureBlack'
Folded: 'darkPurp2 background'
FoldColumn: 'darkPurp background'
SignColumn: 'darkPurp background'
IncSearch: 'pureWhite darkPurp'
#Substitute: ''
LineNr: 'darkPurp background'
MatchParen: 'pureWhite darkPurp'
ModeMsg: 'purple'
#MsgArea: ''
#MsgSeparator: ''
MoreMsg: 'purple'
NonText: '@EndOfBuffer'
#NormalFloat: ''
#NormalNC: ''
Pmenu: 'foreground visualSel'
PmenuSel: 'pureWhite darkPurp'
PmenuSbar: '- darkPurp'
PmenuThumb: '- darkPurp2'
Question: 'purple'
QuickFixLine: 'foreground cursorLine'
Search: 'pureWhite darkPurp2'
SpecialKey: 'orange background'
SpellBad: 'red - u'
SpellLocal: 'foreground - u'
SpellCap: 'green - u'
SpellRare: 'yellow - u'
StatusLine: 'foreground background r'
StatusLineTerm: '@StatusLine'
StatusLineTermNC: 'pureBlack darkPurp r'
StatusLineNC: '@StatusLineTermNC'
TabLine: 'pureBlack grey'
TabLineFill: 'grey pureBlack'
TabLineSel: 'grey2 background'
Visual: '- visualSel'
VisualNOS: '@Visual'
WarningMsg: 'orange background'
WildMenu: 'pureBlack grey2'
Whitespace: '@EndOfBuffer'
diffAdded: 'purple -'
diffRemoved: 'red -'

#Gui
#Menu: ''
#Scrollbar: ''
#Tooltip: ''

# BASE SYNTAX
Normal: 'foreground background'
Comment: 'darkPurp'     # 1
Constant: 'yellow'      # 2
Identifier: 'cyan'      # 3
Statement: 'green'      # 4
PreProc: 'purple'       # 5
Type: 'magenta'         # 6
Special: 'purple'       # 7
Underlined: 'green - u' # 8
Error: 'red'            # 9
Ignore: 'red'
Delimiter: 'foreground'
Operator: 'magenta'
Tag: 'purple'
Debug: 'purple'
StorageClass: 'purple'
String: 'cyan'
Structure: 'cyan'
Typedef: 'cyan'
Function: 'green'
Include: 'green'
Label: 'green'
Exception: 'orange'
Keyword: 'orange'
SpecialChar: 'orange'
Boolean: 'yellow'
Character: 'yellow'
Float: 'yellow'
Number: 'yellow'
Conditional: 'green'
Repeat: 'green'
Title: 'purple2'
Define: 'purple2'
Macro: 'purple2'
PreCondit: 'purple2'
SpecialComment: '@Comment'
Todo: 'pureWhite darkPurp2 u'

# LANGUAGE SPECIFICS
# C
cFormat: '@Title'
cCppOutIf1: '@Normal'
cCppOutIf2: '@Normal'
cBracket: '@Title'
#cOperator: '@Type'

# C++

# CSS
cssBraces: '@Normal'
cssSelectorOp: 'magenta'

# Fortran
fortranType: '@Tag'
fortranStructure: '@Structure'
fortranStorageClass: '@StorageClass'
fortranUnitHeader: '@Title'

# Haskell
haskellType: '@Tag'
haskellIdentifier: '@Label'
haskellKeyword: '@Boolean'
haskellDecl: '@Boolean'
#haskellDelimeter: '@Operator'
#haskellOperators: '@Title'

# HTML
htmlTagName: '@Function'
htmlEndTag: '@Conditional'
htmlArg: '@Tag'
htmlSpecialTagName: '@Type'

# Java
javaClassDecl: '@Structure'
javaTypeDef: '@Keyword'

# Javascript
jsStorageClass: '@Title'
jsFunction: '@Function'
jsFuncName: '@Special'
jsOperator: '@Operator'
jsNull: '@Constant'
jsGlobalObjects: '@Constant'
jsFuncCall: '@Function'
jsOperatorKeyword: '@Operator'
jsExceptions: '@Error'
jsObjectProp: '@Tag'
jsTernaryIfOperator: '@Title'
jsTemplateBraces: '@Title'
jsTemplateExpression: '@String'

# lAtEx
texTypeStyle: '@Special'

# Markdown
mkdDelimiter: '@Normal'

# PHP
phpInclude: '@Conditional'
phpKeyword: '@StorageClass'
phpMemberSelector: '@Title'
phpVarSelector: '@Title'

# Python 
pythonOperator: 'magenta'

# Ruby
rubyConstant: '@Constant'
rubyDefine: '@Define'
rubyMethodName: '@Function'
rubyInstanceVariable: '@Tag'
rubyKeywordAsMethod: '@Tag'

# Typescript
typescriptProp: '@Tag'
typescriptVariable: '@Title'
jsxTagName: '@HTMLTagName'
jsxComponentName: '@Tag'
jsxOpenPunct: '@jsxTagName'
jsxClosePunct: '@jsxOpenPunct'
jsxCloseString: '@jsxClosePunct'
typescriptBraces: '@Normal'
typescriptArrowFunc: 'magenta'
typescriptNumberStaticMethod: '@Function'
typescriptNumberMethod: '@Function'
typescriptStringStaticMethod: '@Function'
typescriptStringMethod: '@Function'
typescriptArrayStaticMethod: '@Function'
typescriptArrayMethod: '@Function'
typescriptObjectStaticMethod: '@Function'
typescriptObjectMethod: '@Function'
typescriptSymbolStaticMethod: '@Function'
typescriptFunctionMethod: '@Function'
typescriptMathStaticMethod: '@Function'
typescriptDateStaticMethod: '@Function'
typescriptDateMethod: '@Function'
typescriptJSONStaticMethod: '@Function'
typescriptRegExpMethod: '@Function'
typescriptES6MapMethod: '@Function'
typescriptES6SetMethod: '@Function'
typescriptPromiseStaticMethod: '@Function'
typescriptPromiseMethod: '@Function'
typescriptReflectMethod: '@Function'
typescriptIntlMethod: '@Function'
typescriptBOMNavigatorMethod: '@Function'
typescriptServiceWorkerMethod: '@Function'
typescriptBOMLocationMethod: '@Function'
typescriptBOMHistoryMethod: '@Function'
typescriptConsoleMethod: '@Function'
typescriptXHRMethod: '@Function'
typescriptFileMethod: '@Function'
typescriptFileReaderMethod: '@Function'
typescriptFileListMethod: '@Function'
typescriptBlobMethod: '@Function'
typescriptURLStaticMethod: '@Function'
typescriptSubtleCryptoMethod: '@Function'
typescriptCryptoMethod: '@Function'
typescriptHeadersMethod: '@Function'
typescriptRequestMethod: '@Function'
typescriptResponseMethod: '@Function'
typescriptCacheMethod: '@Function'
typescriptEncodingMethod: '@Function'
typescriptGeolocationMethod: '@Function'
typescriptPaymentMethod: '@Function'
typescriptPaymentResponseMethod: '@Function'
typescriptDOMNodeMethod: '@Function'
typescriptDOMDocMethod: '@Function'
typescriptDOMEventTargetMethod: '@Function'
typescriptDOMEventMethod: '@Function'
typescriptDOMStorageMethod: '@Function'
typescriptDOMFormMethod: '@Function'


#Vim
vimGroupName: '@Normal'

# YAML
yamlKeyValueDelimiter: '@Normal'
yamlBlockMappingKey: '@Function'

# PLUGINS
#Vista
vistaTag: '@Conditional'
vistaIcon: '@Identifier'
vistaColon: '@Normal'
vistaScope: '@Constant'
vistaKind: '@Conditional'

# Sneak
Sneak: 'pureBlack yellow'
